# Generated by Django 4.2.6 on 2024-01-30 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dept',
            old_name='d_name',
            new_name='dept_name',
        ),
    ]
